before:
  hooks:
    - go mod tidy -v
builds:
  - id: nodekeep-agent-linux
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - arm64
      - amd64
    main: ./cmd/agent
    binary: nodekeep-agent
  - id: nodekeep-agent-darwin
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - arm64
      - amd64
    main: ./cmd/agent
    binary: nodekeep-agent
  - id: nodekeep-agent-windows
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
    main: ./cmd/agent
    binary: nodekeep-agent
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{.ProjectName}}"
archives:
  - name_template: "nodekeep-agent_{{ .Os }}_{{ .Arch }}"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
